ALTER TABLE photobooth_rooms
  ADD COLUMN host_peer_id VARCHAR(128) DEFAULT NULL,
  ADD COLUMN guest_peer_id VARCHAR(128) DEFAULT NULL,
  ADD COLUMN host_joined_at TIMESTAMP NULL DEFAULT NULL,
  ADD COLUMN guest_joined_at TIMESTAMP NULL DEFAULT NULL;

ALTER TABLE photobooth_captures
  ADD COLUMN capture_type VARCHAR(16) NOT NULL DEFAULT 'single',
  ADD COLUMN shots_json LONGTEXT DEFAULT NULL,
  ADD COLUMN options_json LONGTEXT DEFAULT NULL,
  MODIFY COLUMN strip_url LONGTEXT DEFAULT NULL;
