-- Run this file in Supabase: SQL Editor -> New query -> Run.
-- All app access is through the Vercel API, not directly from the browser.

create table if not exists public.photobooth_rooms (
  id bigint generated by default as identity primary key,
  room_code char(5) not null unique,
  room_mode text not null default 'ldr' check (room_mode in ('together', 'ldr')),
  host_peer_id varchar(128),
  guest_peer_id varchar(128),
  host_joined_at timestamptz,
  guest_joined_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.photobooth_room_participants (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.photobooth_rooms(id) on delete cascade,
  role text not null check (role in ('host', 'guest')),
  peer_id varchar(128),
  joined_at timestamptz not null default now()
);

create table if not exists public.photobooth_captures (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.photobooth_rooms(id) on delete cascade,
  capture_token varchar(64) not null unique,
  capture_type varchar(16) not null default 'single',
  title varchar(120) not null default 'Boothly',
  theme varchar(32) not null default 'cream',
  strip_url text,
  shots_json jsonb,
  options_json jsonb,
  created_at timestamptz not null default now()
);

create index if not exists photobooth_room_participants_room_id_idx
  on public.photobooth_room_participants(room_id);
create index if not exists photobooth_captures_room_id_idx
  on public.photobooth_captures(room_id);

-- These tables are not public. Vercel uses the private secret key server-side.
alter table public.photobooth_rooms enable row level security;
alter table public.photobooth_room_participants enable row level security;
alter table public.photobooth_captures enable row level security;
